#!/bin/bash

DEFAULT_ROUTE=$(ip route show default | awk '/default/ {print $3}')
JUDGE_IF_HOTSPOT=$(echo $DEFAULT_ROUTE | awk -F '.' '{ print $4 }')
if [[ $JUDGE_IF_HOTSPOT = 1 ]]; then
  adb connect "192.168.3.66:5555"
else
  adb connect "$DEFAULT_ROUTE:5555"
fi
nohup scrcpy --shortcut-mod lctrl --push-target /sdcard/Pictures &
