gui:
    # stuff relating to the UI
    scrollHeight: 2 # how many lines you scroll by
    scrollPastBottom: true # enable scrolling past the bottom
    sidePanelWidth: 0.3333 # number from 0 to 1
    expandFocusedSidePanel: false
    mainPanelSplitMode: 'flexible' # one of 'horizontal' | 'flexible' | 'vertical'
    theme:
      lightTheme: false # For terminals with a light background
      activeBorderColor:
        - blue
        - bold
      inactiveBorderColor:
        - black
      optionsTextColor:
        - purple
      selectedLineBgColor:
        - reverse
      selectedRangeBgColor:
        - reverse
    commitLength:
      show: true
    mouseEvents: true
    skipUnstageLineWarning: false
    skipStashWarning: true
git:
    paging:
      colorArg: always
      useConfig: false
    merging:
      # only applicable to unix users
      manualCommit: false
      # extra args passed to `git merge`, e.g. --no-ff
      args: ""
    pull:
      mode: 'merge' # one of 'merge' | 'rebase' | 'ff-only'
    skipHookPrefix: WIP
    autoFetch: true
    branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --"
    allBranchesLogCmd: "git log --graph --all --color=always --abbrev-commit --decorate --date=relative  --pretty=medium"
    overrideGpg: false # prevents lazygit from spawning a separate process when using GPG
    disableForcePushing: false
update:
    method: prompt # can be: prompt | background | never
    days: 14 # how often an update is checked for
reporting: 'undetermined' # one of: 'on' | 'off' | 'undetermined'
confirmOnQuit: false
# determines whether hitting 'esc' will quit the application when there is nothing to cancel/close
quitOnTopLevelReturn: true
disableStartupPopups: false
notARepository: 'prompt' # one of: 'prompt' | 'create' | 'skip'
