#mpv searches for subtitle files in these directories:
#
#    /path/to/video/
#    /path/to/video/sub/
#    /path/to/video/subtitles/
#    the sub configuration subdirectory (usually ~/.config/mpv/sub/)
sub-file-paths=sub:subtitles
